support coredumps: for dev=true single node docker instances & stop_project clean

diff --git a/run_project b/run_project
--- a/run_project
+++ b/run_project
@@ -26,18 +26,41 @@ if [[ "${USE_COMPOSE}" == true ]]; then
         docker exec -it "${PM1}" provision "${PM1}" "${PM2}" "${PM3}"
     fi
 else
-    docker run -d \
-        --name "${PM1}" \
-        --hostname "${PM1}" \
-        --env PM1="${PM1}" \
-        --env USE_S3_STORAGE="${USE_S3_STORAGE}" \
-        --env S3_ACCESS_KEY_ID="${S3_ACCESS_KEY_ID}" \
-        --env S3_SECRET_ACCESS_KEY="${S3_SECRET_ACCESS_KEY}" \
-        --env S3_BUCKET="${S3_BUCKET}" \
-        --env S3_ENDPOINT="${S3_ENDPOINT}" \
-        --env S3_REGION="${S3_REGION}" \
-        --env CGROUP="${CGROUP}" \
-        -p 127.0.0.1:3307:3306 \
-        --shm-size=512mb "${MCS_IMAGE_NAME}"
-    docker exec -it "${PM1}" provision "${PM1}"
+
+    ADDITIONAL_ARGS=""
+    if [[ "${DEV}" == true ]]; then
+        if [ -f build ]; then
+            if bash build ; then
+                ADDITIONAL_ARGS=" --privileged --ulimit core=-1 --cap-add=SYS_PTRACE "
+            else
+                echo "Failed to build"
+                exit 1;
+            fi
+        fi
+    fi;
+
+    if [ "$(docker ps -a --filter "name=$PM1" --format '{{.Names}}')" == "${PM1}" ]; then
+        echo "Container ${PM1} already exists - starting container..."
+        docker start $PM1
+    else 
+        docker run -d \
+            --name "${PM1}" \
+            --hostname "${PM1}" \
+            --env PM1="${PM1}" \
+            --env USE_S3_STORAGE="${USE_S3_STORAGE}" \
+            --env S3_ACCESS_KEY_ID="${S3_ACCESS_KEY_ID}" \
+            --env S3_SECRET_ACCESS_KEY="${S3_SECRET_ACCESS_KEY}" \
+            --env S3_BUCKET="${S3_BUCKET}" \
+            --env S3_ENDPOINT="${S3_ENDPOINT}" \
+            --env S3_REGION="${S3_REGION}" \
+            --env CGROUP="${CGROUP}" $ADDITIONAL_ARGS \
+            -p 127.0.0.1:3307:3306 \
+            --shm-size=512mb "${MCS_IMAGE_NAME}"
+        docker exec -it "${PM1}" provision "${PM1}"
+    fi;
+
+    if [[ "${DEV}" == true ]]; then
+        docker exec $PM1 sh -c "echo '/core.%e.%p' > /proc/sys/kernel/core_pattern"
+    fi;
+    
 fi
