DBAAS-4851 - SkySQL specific changes for k8s

diff --git a/scripts/columnstore-init b/scripts/columnstore-init
--- a/scripts/columnstore-init
+++ b/scripts/columnstore-init
@@ -238,6 +238,23 @@ if [[ $(hostname -s) == "$PM1" ]]; then
         fi
         echo 'MaxScale user created'
 
+        if [ $SKYSQL_INITIALIZATION -eq 1 ] && [ -d "/mnt/skysql/columnstore-container-scripts" ]; then
+            for f in /mnt/skysql/columnstore-container-scripts/*; do
+                case "$f" in
+                    *.sql)
+                        echo "$0: running $f"
+                        "$MCS_INSTALL_BIN/mariadb" < "$f"
+                        if [ $? -ne 0 ]; then
+                            echo "ERROR: Wasn't able to initialize SkySQL specific users."
+                            exit 1
+                        fi
+                        echo
+                        ;;
+                esac
+            echo
+            done
+        fi
+
         # Securing MariaDB Installation
         $MCS_INSTALL_BIN/mariadb -e "
             DROP DATABASE IF EXISTS test;
@@ -321,6 +338,7 @@ fi
 # Clean Remnants
 rm -f /var/lib/mysql/*.err
 
+# Mark Container Initialized
 touch $IFLAG
 
 # Return To cmapi-start
