API Key fixes

diff --git a/scripts/columnstore-init b/scripts/columnstore-init
--- a/scripts/columnstore-init
+++ b/scripts/columnstore-init
@@ -10,16 +10,16 @@ JEMALLOC_PATH="/usr/lib64/libjemalloc.so.2"
 export LD_PRELOAD=$JEMALLOC_PATH
 
 # Set StorageManager Defaults
-ASYNC_CONN="${ASYNC_CONN:-0}"
-ANALYTICS_ONLY="${ANALYTICS_ONLY:-0}"
-USE_S3_STORAGE="${USE_S3_STORAGE:-0}"
+ASYNC_CONN=${ASYNC_CONN:-0}
+ANALYTICS_ONLY=${ANALYTICS_ONLY:-0}
+USE_S3_STORAGE=${USE_S3_STORAGE:-0}
 
 # Set Credential Defaults
-CEJ_USER="${CEJ_USER:-cej}"
-CEJ_PASSWORD="${CEJ_PASSWORD:-C0lumnStore!}"
-REP_USER="${REP_USER:-idbrep}"
-REP_PASSWORD="${REP_PASSWORD:-C0lumnStore!}"
-API_KEY="${API_KEY:-somekey123}"
+CEJ_USER=${CEJ_USER:-cej}
+CEJ_PASSWORD=${CEJ_PASSWORD:-C0lumnStore!}
+REP_USER=${REP_USER:-idbrep}
+REP_PASSWORD=${REP_PASSWORD:-C0lumnStore!}
+API_KEY=${API_KEY:-somekey123}
 
 # Set Resource Variables
 SERVER_SUBNET=$(hostname -i | cut -d "." -f 1-3 -s)
@@ -122,6 +122,12 @@ $MCS_INSTALL_BIN/dbbuilder 7 &> $LOG_PREFIX/dbbuilder.log
 
 MARIADB_RUNNING=$(mariadb-admin ping)
 if [[ $MARIADB_RUNNING == *"alive"* ]]; then
+  # Disable Cracklib
+  $MCS_INSTALL_BIN/mariadb -e "UNINSTALL SONAME 'cracklib_password_check.so';"
+  if [ $? -ne 0 ]; then
+      echo "ERROR: Deactivating Cracklib"
+      exit 1
+  fi
   # Set Up Cross Engine Join User
   $MCS_INSTALL_BIN/mariadb -e "GRANT SELECT ON *.* TO 'cej'@'127.0.0.1' IDENTIFIED BY '$CEJ_PASSWORD';"
   if [ $? -ne 0 ]; then
@@ -148,6 +154,10 @@ if [[ $MARIADB_RUNNING == *"alive"* ]]; then
               MASTER_USE_GTID=slave_pos,
               MASTER_CONNECT_RETRY=10;
               START SLAVE;"
+    if [ $? -ne 0 ]; then
+        echo "ERROR: Performing CHANGE MASTER on Replica"
+        exit 1
+    fi
     sed -i "s|read_only = OFF|read_only = ON|" /etc/my.cnf.d/columnstore.cnf
   fi
   unset REP_PASSWORD
@@ -155,6 +165,12 @@ if [[ $MARIADB_RUNNING == *"alive"* ]]; then
   $MCS_INSTALL_BIN/mariadb -e "DROP DATABASE IF EXISTS test; DELETE FROM mysql.user WHERE User='';"
   if [ $? -ne 0 ]; then
       echo "ERROR: Securing mariadb"
+      exit 1
+  fi
+  # Enable Cracklib
+  $MCS_INSTALL_BIN/mariadb -e "INSTALL SONAME 'cracklib_password_check.so';"
+  if [ $? -ne 0 ]; then
+      echo "ERROR: Activating Cracklib"
       exit 1
   fi
 fi
