start/stop script updates

diff --git a/scripts/mcs-start b/scripts/mcs-start
--- a/scripts/mcs-start
+++ b/scripts/mcs-start
@@ -9,6 +9,9 @@ CMAPI_KEY="${CMAPI_KEY:-somekey123}"
 TOTALUMMEMORY="${TOTALUMMEMORY:-25%}"
 NUMBLOCKSPCT="${NUMBLOCKPCT:-50}"
 SKYSQL_INITIALIZATION="${SKYSQL_INITIALIZATION:-0}"
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+NC='\033[0m'
 
 # Dynamic Memory Allocation
 if [ -f /sys/fs/cgroup/memory/memory.limit_in_bytes ] && [ "$(cat /sys/fs/cgroup/memory/memory.limit_in_bytes)" -le "$(free -b | awk 'NR==2{printf "%d", $2 }')" ]; then
@@ -27,7 +30,12 @@ xmlstarlet ed -L -u '/Columnstore/DBBC/NumBlocksPct' -v "$NUMBLOCKSPCT" $COLXML
 touch $LOG_PREFIX/cmapi_server.log && chmod 666 $LOG_PREFIX/cmapi_server.log
 cd /usr/share/columnstore/cmapi || exit
 PYTHONPATH=/usr/share/columnstore/cmapi/deps /usr/share/columnstore/cmapi/python/bin/python3 -m cmapi_server &> $LOG_PREFIX/cmapi_server.log &
-echo CMAPI PID = $!
+if [[ $? -eq 0 ]]; then
+    printf "Starting Cluster Manager API... ${GREEN}done${NC}\n"
+else
+    printf "Starting Cluster Manager API... ${RED}fail${NC}\n"
+    exit 1
+fi
 
 # Intialize Container If Necessary
 if [ ! -e $IFLAG ]; then
@@ -40,12 +48,15 @@ fi
 
 # Start MariaDB & Columnstore
 mariadb-admin ping > /dev/null 2>&1
-
 if [[ $? -ne 0 ]]; then
-    mariadbd-safe &
+    mariadbd-safe  > /dev/null 2>&1 &
+    if [[ $? -eq 0 ]]; then
+        printf "Starting MariaDB Server... ${GREEN}done${NC}\n"
+    else
+        printf "Starting MariaDB Server... ${RED}fail${NC}\n"
+        exit 1
+    fi
     sleep 5
 fi
-
-mcs cluster restart > /dev/null 2>&1
 
 exit 0
diff --git a/scripts/mcs-stop b/scripts/mcs-stop
--- a/scripts/mcs-stop
+++ b/scripts/mcs-stop
@@ -2,11 +2,37 @@
 
 # Set Variables
 CMAPI_PID=$(pgrep -f cmapi_server)
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+NC='\033[0m'
 
-# Stop System
-echo 'Stopping Cluster Manager API...'
-mcs cluster stop > /dev/null 2>&1
+echo "Shutting Down System"
 
+# Stop Columnstore
+mcs cluster stop  > /dev/null 2>&1
+if [[ $? -eq 0 ]]; then
+    printf "Stopping ColumnStore Cluster... ${GREEN}done${NC}\n"
+else
+    printf "Stopping ColumnStore Cluster... ${RED}fail${NC}\n"
+    exit 1
+fi
+
+# Stop CMAPI
 if [[ ! -z $CMAPI_PID ]]; then
     kill $CMAPI_PID > /dev/null
+    if [[ $? -eq 0 ]]; then
+        printf "Stopping Cluster Manager API... ${GREEN}done${NC}\n"
+    else
+        printf "Stopping Cluster Manager API... ${RED}fail${NC}\n"
+        exit 1
+    fi
+fi
+
+# Stop MariaDB
+mariadb-admin shutdown
+if [[ $? -eq 0 ]]; then
+    printf "Stopping MariaDB Server... ${GREEN}done${NC}\n"
+else
+    printf "Stopping MariaDB Server... ${RED}fail${NC}\n"
+    exit 1
 fi
