Dynamic Memory Fix

diff --git a/scripts/mcs-start b/scripts/mcs-start
--- a/scripts/mcs-start
+++ b/scripts/mcs-start
@@ -6,54 +6,53 @@ IFLAG='/etc/columnstore/container-initialized'
 LOG_PREFIX='/var/log/mariadb/columnstore'
 MCS_INSTALL_BIN='/usr/bin'
 CMAPI_KEY="${CMAPI_KEY:-somekey123}"
-TOTALUMMEMORY="${TOTALUMMEMORY:-25%}"
-NUMBLOCKSPCT="${NUMBLOCKPCT:-50}"
 SKYSQL_INITIALIZATION="${SKYSQL_INITIALIZATION:-0}"
 RED='\033[0;31m'
 GREEN='\033[0;32m'
+CYAN='\033[0;36m'
 NC='\033[0m'
 
-# Dynamic Memory Allocation
-if [ -f /sys/fs/cgroup/memory/memory.limit_in_bytes ] && [ "$(cat /sys/fs/cgroup/memory/memory.limit_in_bytes)" -le "$(free -b | awk 'NR==2{printf "%d", $2 }')" ]; then
-    # If limited by cgroups (e.g. in SkySQL)
-    MAX_RAM_BYTES=$(cat /sys/fs/cgroup/memory/memory.limit_in_bytes)
-    MAX_RAM=$((MAX_RAM_BYTES/1024/1024))
-    TOTALUMMEMORY=$( echo $MAX_RAM / 4  | bc )M
-    NUMBLOCKSPCT=$( echo $MAX_RAM / 2  | bc )M
-fi
-
-# Performance Tuning
-xmlstarlet ed -L -u '/Columnstore/HashJoin/TotalUmMemory' -v "$TOTALUMMEMORY" $COLXML
-xmlstarlet ed -L -u '/Columnstore/DBBC/NumBlocksPct' -v "$NUMBLOCKSPCT" $COLXML
+# Begin
+echo -e "${CYAN}***** Starting ColumnStore System *****${NC}"
 
 # Start CMAPI
-touch $LOG_PREFIX/cmapi_server.log && chmod 666 $LOG_PREFIX/cmapi_server.log
+touch "${LOG_PREFIX}"/cmapi_server.log && chmod 666 "${LOG_PREFIX}"/cmapi_server.log
 cd /usr/share/columnstore/cmapi || exit
-PYTHONPATH=/usr/share/columnstore/cmapi/deps /usr/share/columnstore/cmapi/python/bin/python3 -m cmapi_server &> $LOG_PREFIX/cmapi_server.log &
-if [[ $? -eq 0 ]]; then
-    printf "Starting Cluster Manager API... ${GREEN}done${NC}\n"
+if PYTHONPATH=/usr/share/columnstore/cmapi/deps /usr/share/columnstore/cmapi/python/bin/python3 -m cmapi_server &> "${LOG_PREFIX}"/cmapi_server.log &
+then
+    echo -e "Starting Cluster Manager API... ${GREEN}done${NC}"
 else
-    printf "Starting Cluster Manager API... ${RED}fail${NC}\n"
+    echo -e "Starting Cluster Manager API... ${RED}fail${NC}"
     exit 1
 fi
 
 # Intialize Container If Necessary
-if [ ! -e $IFLAG ]; then
-    $MCS_INSTALL_BIN/columnstore-init &> $LOG_PREFIX/columnstore-init.log
-    if [ $? -ne 0 ]; then
+if [[ ! -e ${IFLAG} ]]; then
+    if ! "${MCS_INSTALL_BIN}"/columnstore-init &> "${LOG_PREFIX}"/columnstore-init.log; then
         echo "ERROR: During Initialization."
         exit 1
     fi
 fi
 
+# Dynamic Memory Allocation
+MEMORY_PCT_LIMIT="${MEMORY_PCT_LIMIT:-90}"
+MAX_RAM_KB=$(grep MemTotal /proc/meminfo | cut -d':' -f2 | sed 's/ //g;s/[^0-9]//g')
+MAX_RAM=$((MAX_RAM_KB*MEMORY_PCT_LIMIT/100/1024))
+TOTALUMMEMORY=$( echo "${MAX_RAM}" / 4  | bc )M
+NUMBLOCKSPCT=$( echo "${MAX_RAM}" / 2  | bc )M
+
+# Performance Tuning
+xmlstarlet ed -L -u '/Columnstore/HashJoin/TotalUmMemory' -v "${TOTALUMMEMORY}" "${COLXML}"
+xmlstarlet ed -L -u '/Columnstore/DBBC/NumBlocksPct' -v "${NUMBLOCKSPCT}" "${COLXML}"
+
 # Start MariaDB & Columnstore
 mariadb-admin ping > /dev/null 2>&1
-if [[ $? -ne 0 ]]; then
-    mariadbd-safe  > /dev/null 2>&1 &
-    if [[ $? -eq 0 ]]; then
-        printf "Starting MariaDB Server... ${GREEN}done${NC}\n"
+if ! mariadb-admin ping > /dev/null 2>&1; then
+    if mariadbd-safe > /dev/null 2>&1 &
+    then
+        echo -e "Starting MariaDB Server... ${GREEN}done${NC}"
     else
-        printf "Starting MariaDB Server... ${RED}fail${NC}\n"
+        echo -e "Starting MariaDB Server... ${RED}fail${NC}"
         exit 1
     fi
     sleep 5
diff --git a/scripts/provision b/scripts/provision
--- a/scripts/provision
+++ b/scripts/provision
@@ -3,6 +3,9 @@
 CMAPI_KEY="${CMAPI_KEY:-somekey123}"
 MAXSCALE="${MAXSCALE:-false}"
 IFLAG='/etc/columnstore/container-initialized'
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+NC='\033[0m'
 
 HOSTS=( "$@" )
 if [[ "$#" -eq 0 ]]; then
@@ -14,36 +17,30 @@ for e in "${HOSTS[@]}"; do
     EXPANDED+=("--node ${e}")
 done
 
-RED='\033[0;31m'
-GREEN='\033[0;32m'
-NC='\033[0m'
-
 # Wait For Primary Node To Start
-if [ ! -f $IFLAG ]; then
-    echo -n 'Waiting for PM1 to be initialized '
-    while [ ! -f $IFLAG ]
+if [[ ! -f ${IFLAG} ]]; then
+    echo -n 'Waiting for PM1 To Be Initialized '
+    while [[ ! -f ${IFLAG} ]]
     do
         printf "."
         sleep 2
     done
-    printf " ${GREEN}done${NC}\n"
+    echo -e " ${GREEN}done${NC}"
 fi
 
 sleep 3
 
 # Set API Key
-mcs cluster set api-key --key $CMAPI_KEY > /dev/null 2>&1
-if [ $? -ne 0 ]; then
+if ! mcs cluster set api-key --key "${CMAPI_KEY}" > /dev/null 2>&1; then
     echo "Failed Setting API Key"
     exit 1
 fi
 
 # Add Nodes To System
-mcs cluster node add "${EXPANDED[@]}" > /dev/null 2>&1
-if [[ $? -eq 0 ]]; then
-    printf "Adding PMs to Cluster ... ${GREEN}done${NC}\n"
+if mcs cluster node add "${EXPANDED[@]}" > /dev/null 2>&1; then
+    echo -e "Adding PMs To Cluster ... ${GREEN}done${NC}"
 else
-    printf "Adding PMs to Cluster ... ${RED}fail${NC}\n"
+    echo -e "Adding PMs To Cluster ... ${RED}fail${NC}"
     exit 1
 fi
 
@@ -51,14 +48,22 @@ if [[ ${MAXSCALE} == true ]]; then
     provision-mxs
 fi
 
-sleep 30
+# Wait For ColumnStore To Be Ready
+READY=$(mariadb -sN -e "SELECT mcsSystemReady();")
+echo -n 'Waiting For Columnstore To Be Ready ...'
+while [[ ${READY} -eq 0 ]]
+do
+    printf "."
+    sleep 2
+done
+echo -e " ${GREEN}done${NC}"
 
 # Validate
 QUERY=$(mariadb -sN -e "DROP DATABASE IF EXISTS validate; CREATE DATABASE validate; CREATE TABLE validate.sample (id INT) ENGINE=columnstore; INSERT INTO validate.sample VALUES (99); SELECT id FROM validate.sample;" 2>&1)
-if [[ $? = 0 ]] && [[ ${QUERY} = 99 ]]; then
-    printf "Validating ColumnStore engine ... ${GREEN}done${NC}\n"
+if [[ ${QUERY} = 99 ]]; then
+    echo -e "Validating ColumnStore Engine ... ${GREEN}done${NC}"
     mariadb -e "DROP DATABASE IF EXISTS validate;" 2>&1
 else
-    printf "Validating ColumnStore engine ... ${RED}fail${NC}\n"
+    echo -e "Validating ColumnStore Engine ... ${RED}fail${NC}"
     exit 1
 fi
