Updates

diff --git a/scripts/mcs-start b/scripts/mcs-start
--- a/scripts/mcs-start
+++ b/scripts/mcs-start
@@ -3,6 +3,7 @@
 # Set Some Variables
 COLXML='/etc/columnstore/Columnstore.xml'
 IFLAG='/etc/columnstore/container-initialized'
+PFLAG='/etc/columnstore/container-provisioned'
 LOG_PREFIX='/var/log/mariadb/columnstore'
 MCS_INSTALL_BIN='/usr/bin'
 CMAPI_KEY="${CMAPI_KEY:-somekey123}"
@@ -31,7 +32,7 @@ if [[ "${SKYSQL_INITIALIZATION}" == 1 ]]; then
     xmlstarlet ed -L -u '/Columnstore/DBBC/NumBlocksPct' -v "${NUMBLOCKSPCT}" "${COLXML}"
 fi
 
-# Start CMAPI & Columnstore
+# Start CMAPI
 touch "${LOG_PREFIX}"/cmapi_server.log && chmod 666 "${LOG_PREFIX}"/cmapi_server.log
 cd /usr/share/columnstore/cmapi || exit
 if PYTHONPATH=/usr/share/columnstore/cmapi/deps /usr/share/columnstore/cmapi/python/bin/python3 -m cmapi_server &> /dev/null &
@@ -40,6 +41,16 @@ then
 else
     echo -e "Starting Cluster Manager API... ${RED}fail${NC}"
     exit 1
+fi
+
+# Start Columnstore
+if [[ -e ${PFLAG} ]]; then
+    if mcs cluster start  > /dev/null 2>&1; then
+        echo -e "Starting ColumnStore Cluster... ${GREEN}done${NC}"
+    else
+        echo -e "Starting ColumnStore Cluster... ${RED}fail${NC}"
+        exit 1
+    fi
 fi
 
 # Start MariaDB
diff --git a/scripts/mcs-stop b/scripts/mcs-stop
--- a/scripts/mcs-stop
+++ b/scripts/mcs-stop
@@ -27,3 +27,13 @@ if [[ -n ${CMAPI_PID} ]]; then
         exit 1
     fi
 fi
+
+# Stop MariaDB
+if mariadb-admin ping > /dev/null 2>&1; then
+    if mariadb-admin shutdown > /dev/null 2>&1; then
+        echo -e "Stopping MariaDB Server... ${GREEN}done${NC}"
+    else
+        echo -e "Stopping MariaDB Server... ${RED}fail${NC}"
+        exit 1
+    fi
+fi
